### ISSUE TITLE
Issue setting env variable

### ISSUE THREAD

**Issue by magicmark** [composerize/composerize#1]
https://www.reddit.com/r/docker/comments/50822n/made_a_thing_to_turn_docker_run_commands_into/d72lj63:

> This doesn't work for when I have an environment variable such as
> `-e PS1="\[\033[01;31m\]\u\[\033[01;32m\]@\h\[\033[01;34m\] \w \$\[\033[00m\] "`

**Comment by sharevb** [comment]
Currently got this, not sure it is good or not :
```
       environment:
            - 'PS1=\[\033[01;31m\]\u\[\033[01;32m\]@\h\[\033[01;34m\] \w \$\[\033[00m\] '

```

**Comment by sharevb** [comment]
Actually docker run current behavior is to remove double quote of forms -e XXX="xxx" and send XXX=xxx to container, so this is solved by my PR https://github.com/magicmark/composerize/pull/571 deployed at https://deploy-preview-571--composerize.netlify.app/

**Comment by sharevb** [comment]
Should be ok in the latest version
