### ISSUE TITLE
How does the CLI specify the version parameter?

### ISSUE THREAD

**Issue by kyle-kw** [composerize/composerize#604]
**Do you want to request a *feature* or report a *bug*?**

- [x] feature request
- [ ] bug report

**Please provide a sample input docker run command**
```
composerize v3x docker run --log-opt max-size=100m --restart unless-stopped -p 8080:8080 geekyouth/moodist:v1.2.0
```

**What is the current output?***
```
node error
```

**What is the expected/desired output?**
```

```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!

**Comment by kyle-kw** [comment]
and `--help` parameter?

**Comment by sharevb** [comment]
Hi @kyle-kw, will add command line parameters, currently, you can only pass "docker run" commands after composerize without any version option

**Comment by sharevb** [comment]
HI @kyle-kw, should be ok in last version v1.6.7

**Comment by kyle-kw** [comment]
nice job！ @sharevb
