### ISSUE TITLE
missing "--ip" information

### ISSUE THREAD

**Issue by copenhaus** [composerize/composerize#637]
Hi, when I put this line in Composerize website, it's missing the IP address information:

docker run -d --name host --ip 192.168.6.120 -p 81:82 --network ipvlan -v /docker/hosted:/data --hostname host container_name --restart=always

It seemed to be conflicting/ignoring when "--network" is present.

**Comment by sharevb** [comment]
Hi @copenhaus , thanks, should be fixed in latest deployed version
