### ISSUE TITLE
It is ignoring == characters on env variables

### ISSUE THREAD

**Issue by Reister777** [composerize/composerize#639]
**Do you want to request a *feature* or report a *bug*?**
- [ ] feature request
- [ ] bug report

**Please provide a sample input docker run command**
docker rm -f dokemon-agent > /dev/null 2>&1
docker run \
    -e SERVER_URL=http://192.168.1.12:9090 \
    **-e TOKEN=dQufdsfdfsfsadfsadfsdfafasdf2FDuAw==** \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --name dokemon-agent --restart unless-stopped \
    -d productiveops/dokemon-agent:latest
  

**What is the current output?***
It is ignoring == characters on env variable TOKEN:

name: <your project name>
services:
    dokemon-agent:
        environment:
            - SERVER_URL=http://192.168.1.12:9090
            - TOKEN=dQufdsfdfsfsadfsadfsdfafasdf2FDuAw
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: dokemon-agent
        restart: unless-stopped
        image: productiveops/dokemon-agent:latest

**What is the expected/desired output?**
name: <your project name>
services:
    dokemon-agent:
        environment:
            - SERVER_URL=http://192.168.1.12:9090
            - TOKEN=dQufdsfdfsfsadfsadfsdfafasdf2FDuAw==
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: dokemon-agent
        restart: unless-stopped
        image: productiveops/dokemon-agent:latest

**Are you willing/able to attempt a fix?**

- [ X] Is this the case for your issue?
- [X ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!

**Comment by sharevb** [comment]
Hi @Reister777, thanks, should be fixed in latest deployed version
