### ISSUE TITLE
Include an open source license

### ISSUE THREAD

**Issue by GeekSquirrel** [composerize/composerize#648]
Hello, I want to create a bidirectional convertor between 'docker run' and 'compose file' in a single webpage. But I found there is no licenses in this repository (neither does the 'decomposerize' repository). So actually, I can't use this repo legally in such situation because [the official document of github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) says:
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. 

Could you please consider adding one?

**Comment by sharevb** [comment]
Hi @GeekSquirrel, thanks for this good point, actually as the npm package as MIT License as @magicmark pointed out. So I added MIT License to this repository (and will do for decomposerize and composeverter
